name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Mill
        run: |
          curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.6/0.11.6-assembly -o mill
          chmod +x mill

      - name: Run Tests
        run: ./mill zioNats.test

      - name: Compile Project
        run: ./mill zioNats.compile

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
